services:
  mysql-db:
    image: mysql 
    container_name: rony-commerce-mysql 
    environment: 
      MYSQL_ROOT_PASSWORD: root 
    ports: 
      - 3307:3306 
    networks:  
      - rony-commerce-network
    restart: always 
    
    healthcheck: 
      test: "curl --fail http://rony-commerce-mysql:3306/ || exit 1" 
      timeout: 5s 
      retries: 10  
    deploy:
      resources:
        limits: 
          memory: 512M
    volumes: 
       - db_data:/var/lib/mysql
      
  app:
    image: ronaldliboni/rony-commerce-java
    container_name: rony-commerce-java
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://rony-commerce-mysql:3306/rony-ecommerce?createDatabaseIfNotExist=TRUE
      - storage.bucket=rony-ecommerce-bucket
      - storage.region=us-east-1
      - storage.access-key-id=
      - storage.secret-access-key=
    ports:
     - 8080:8080  
    networks:
      - rony-commerce-network
    restart: on-failure 
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          memory: 512M
        
networks: 
  rony-commerce-network:
    driver: bridge
    
volumes: 
  db_data:
    driver: local