spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/rony-ecommerce?createDatabaseIfNotExist=TRUE
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true