spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/rony-ecommerce?createDatabaseIfNotExist=TRUE
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB        
storage:
    bucket: rony-ecommerce-bucket
    region: us-east-1
    access-key-id: # add your AWS credentials here
    secret-access-key: # add your AWS credentials here