CREATE TABLE IF NOT EXISTS storage_errors (
  id BIGINT NOT NULL AUTO_INCREMENT,
  file_key VARCHAR(36) NOT NULL,
  error_message VARCHAR(255) NOT NULL,
  is_consumed BOOLEAN NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT storage_error_pk PRIMARY KEY (id)
);